Supg incompressible fluid solver
OpenIFEM/OpenIFEM pull request #42
Opened 2022-01-12 14:21 UTC by icbannerman

2022-01-12 16:23 UTC, yufeimi requested changes
1. Too many commits. Merge them. No need for one commit for each test.
2. Your test doesn't check anything about the solution, which makes the tests meaningless. They are simple cases and are almost certain to run.
3. Format.

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +        TimerOutput::Scope timer_section(timer, "Assemble system");
format

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +      if (sigma_pml_field == nullptr)
Remove this pml stuff, not used

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +              if (sigma_pml_field)
remove

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +      std::vector<double> sigma_pml(n_q_points);
Remove

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +      std::vector<Tensor<1, dim>> fsi_acc_values(n_q_points);
For 63-71: I'm certain some of the variables you declare here are not used. Check and remove them.

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +              fe_values[pressure].get_function_values(present_solution,
101-116: Same here. remove unused variables

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +                  const double rho = parameters.fluid_rho *
remove ``ind``

2022-01-12 16:23 UTC, yufeimi commented on source/mpi_insim_supg.cpp
> +                            -(current_velocity_divergence * phi_p[i] )* fe_values.JxW(q);
format!

2022-01-12 16:23 UTC, yufeimi commented on tests/couette_flow_mpi_insim_supg/couette_flow_mpi_insim_supg.cpp
> +
remove nonsense blank lines. Once again, format

2022-01-12 16:23 UTC, yufeimi commented on tests/couette_flow_mpi_insim_supg/couette_flow_mpi_insim_supg.cpp
> +
nonsense blank line

2022-01-12 16:49 UTC, icbannerman commented on tests/couette_flow_mpi_insim_supg/couette_flow_mpi_insim_supg.cpp
> +
thanks for the letting me know all these errors ; I will correct them

2022-01-17 01:00 UTC, yufeimi requested changes

2022-01-19 23:59 UTC, yufeimi requested changes
Check the sentences you wrote. No space before comma or period.

2022-01-19 23:59 UTC, yufeimi commented on tests/fluid_plane_wall_driven_mpi_insim_supg/fluid_plane_wall_driven_mpi_insim_supg.prm
> +  set Dirichlet boundary values = 0, 0, 1 , 0
no space before comma

2022-01-19 23:59 UTC, yufeimi commented on tests/fluid_plane_wall_driven_mpi_insim_supg/fluid_plane_wall_driven_mpi_insim_supg.cpp
> +          double verror = std::abs(vmax - 1.0);
This is a never-failing test, so it's meaningless. Think about why.

2022-01-19 23:59 UTC, yufeimi commented on tests/fluid_plane_wall_driven_mpi_insim_supg/fluid_plane_wall_driven_mpi_insim_supg.cpp
> +          // Check the max values of velocity . The final velocity profile is a
no space before period

2022-02-16 22:09 UTC, merged